site_name: Peering Manager

pages:
  - 'Introduction': 'index.md'
  - 'Setup':
    - 'Peering Manager': 'setup/peering-manager.md'
    - 'Web Server': 'setup/web-server.md'
    - 'LDAP': 'setup/ldap.md'
    - 'Upgrading': 'setup/upgrading.md'
    - 'Scheduled Tasks': 'setup/scheduled-tasks.md'
  - 'User Manual': 'man.md'
  - 'Templating': 'config-template.md'
  - 'Integration': 'integration.md'

markdown_extensions:
  - admonition:
