---
site_name: Peering Manager
site_url: https://peering-manager.readthedocs.io/
repo_url: https://github.com/peering-manager/peering-manager
edit_uri: ""

theme:
  name: material
  logo: media/peering-manager.svg
  favicon: media/peering-manager.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peering-manager/peering-manager
    - icon: fontawesome/brands/slack
      link: https://netdev.chat/
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

nav:
  - Introduction: "introduction.md"
  - Getting Started: "getting-started.md"
  - Installation & Upgrade:
    - "setup/index.md"
    - 1. PostgreSQL: "setup/1-postgresql.md"
    - 2. Redis: "setup/2-redis.md"
    - 3. Peering Manager: "setup/3-peering-manager.md"
    - 4. Web Server:
      - a. Apache 2: "setup/4a-apache2.md"
      - b. nginx: "setup/4b-nginx.md"
    - uWSGI: "setup/uwsgi.md"
    - Upgrading: "setup/upgrading.md"
    - Container Installation: "setup/container.md"
    - Ansible Installation: "setup/ansible.md"
  - Configuration:
    - "configuration/index.md"
    - Required Parameters: "configuration/required-parameters.md"
    - System: "configuration/system.md"
    - Security: "configuration/security.md"
    - Remote Authentication: "configuration/remote-authentication.md"
    - Date & Time: "configuration/date-time.md"
    - Tools: "configuration/tools.md"
    - Miscellaneous: "configuration/miscellaneous.md"
    - Development: "configuration/development.md"
  - Administration:
    - Authentication:
      - "administration/authentication/index.md"
      - LDAP: "administration/authentication/ldap.md"
      - OIDC: "administration/authentication/oidc.md"
      - RADIUS: "administration/authentication/radius.md"
    - Housekeeping: "administration/housekeeping.md"
    - Replication: "administration/replication.md"
  - User Interface: "user-interface.md"
  - Integration:
    - REST API: "integrations/rest-api.md"
    - Webhooks: "integrations/webhooks.md"
    - PeeringDB: "integrations/peeringdb.md"
    - IX-API: "integrations/ix-api.md"
    - Internet Routing Registries: "integrations/irr-prefixes.md"
    - NetBox: "integrations/netbox.md"
    - NAPALM: "integrations/napalm.md"
    - Prometheus Metrics: "integrations/prometheus-metrics.md"
    - Synchronised Data: "integrations/synchronised-data.md"
  - Templating:
    - "templating/index.md"
    - Jinja2 Functions: "templating/jinja2/functions.md"
    - Jinja2 Filters: "templating/jinja2/filters.md"
    - Exposed Variables: "templating/jinja2/variables.md"
    - Templating Tutorial: "templating/tutorial/index.md"
    - Examples:
      - Arista EOS: "templating/examples/arista-eos.md"
      - Cisco IOS XR: "templating/examples/cisco-iosxr.md"
      - Cisco IOS XR as used by AS196610: "templating/examples/cisco-iosxr-as196610.md"
      - Cisco IOS-XR from tutorial: "templating/examples/tutorial-cisco-iosxr.md"
      - Cisco IOS from tutorial: "templating/examples/tutorial-cisco-ios.md"
      - Juniper Junos OS: "templating/examples/juniper-junos.md"
      - Nokia SROS: "templating/examples/nokia-sros.md"
      - VyOS: "templating/examples/tutorial-vyos.md"
      - Peering Request E-Mail: "templating/examples/peering-request-email.md"
      - New Network E-mail: "templating/examples/new-network-email.md"
  - References:
    - Conditions: "reference/conditions.md"
    - Filtering: "reference/filtering.md"
    - Data Model:
      - BGP:
        - Relationship: "models/bgp/relationship.md"
        - Community: "models/bgp/community.md"
      - Core:
        - Data Source: "models/core/datasource.md"
        - Data File: "models/core/datafile.md"
      - Devices:
        - Configuration: "models/devices/configuration.md"
        - Platform: "models/devices/platform.md"
        - Router: "models/devices/router.md"
      - Network:
        - BFD: "models/net/bfd.md"
        - Connection: "models/net/connection.md"
      - Peering:
        - Autonomous System: "models/peering/autonomoussystem.md"
        - BGP Group: "models/peering/bgpgroup.md"
        - Direct Peering Session: "models/peering/directpeeringsession.md"
        - Internet Exchange: "models/peering/internetexchange.md"
        - Internet Exchange Peering Session: "models/peering/internetexchangepeeringsession.md"
        - Routing Policy: "models/peering/routingpolicy.md"
      - Messaging:
        - Contact: "models/messaging/contact.md"
        - Contact Role: "models/messaging/contactrole.md"
        - Contact Assignment: "models/messaging/contactassignment.md"
        - E-mail: "models/messaging/email.md"
      - Extras:
        - Config Context: "models/extras/configcontext.md"
        - Config Context Assigment: "models/extras/configcontextassignment.md"
        - Export Template: "models/extras/exporttemplate.md"
        - IX-API: "models/extras/ixapi.md"
        - Tag: "models/extras/tag.md"
        - Webhook: "models/extras/webhook.md"
      - Token: "models/users/token.md"
  - Development:
    - Getting Started: "development/getting-started.md"
    - Style Guide: "development/style-guide.md"
    - Release Engineering: "development/release-engineering.md"
  - Release Notes:
    - "release-notes/index.md"
    - Version 1.10: "release-notes/version-1.10.md"
    - Version 1.9: "release-notes/version-1.9.md"
    - Version 1.8: "release-notes/version-1.8.md"
    - Version 1.7: "release-notes/version-1.7.md"
    - Version 1.6: "release-notes/version-1.6.md"
    - Version 1.5: "release-notes/version-1.5.md"
    - Version 1.4: "release-notes/version-1.4.md"
    - Version 1.3: "release-notes/version-1.3.md"
    - Version 1.2: "release-notes/version-1.2.md"
    - Version 1.1: "release-notes/version-1.1.md"
    - Version 1.0: "release-notes/version-1.0.md"
