---
site_name: Peering Manager
site_url: https://peering-manager.readthedocs.io/
repo_url: https://github.com/peering-manager/peering-manager
edit_uri: ""
python:
    install:
        - requirements: docs/requirements.txt

theme:
    name: material
    logo: media/peering-manager.svg
    favicon: media/peering-manager.svg
markdown_extensions:
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - footnotes

nav:
    - Introduction: "index.md"
    - Manual installation:
        - 1. PostgreSQL: "setup/1-postgresql.md"
        - 2. Redis: "setup/2-redis.md"
        - 3. Peering Manager: "setup/3-peering-manager.md"
        - 4. Web Server:
            - a. Apache 2: "setup/4a-apache2.md"
            - b. nginx: "setup/4b-nginx.md"
        - 5. Logging (Optional): "setup/5-logging.md"
        - 6. LDAP (Optional): "setup/6-ldap.md"
        - 7. Scheduled Tasks (Optional): "setup/7-scheduled-tasks.md"
        - 8. Prometheus (Optional): "setup/8-prometheus.md"
        - uWSGI: "setup/uwsgi.md"
        - Upgrading: "setup/upgrading.md"
        - Migrate to systemd: "setup/migrate-to-systemd.md"
    - Container Installation: "container.md"
    - Ansible Installation: "ansible.md"
    - Configuration:
        - Configuring: "configuration/index.md"
        - Required Settings: "configuration/required-settings.md"
        - Optional Settings: "configuration/optional-settings.md"
    - User Interface: "user-interface.md"
    - User Manual:
        - Autonomous System: "models/peering/autonomoussystem.md"
        - BGP Group: "models/peering/bgpgroup.md"
        - Community: "models/peering/community.md"
        - Configuration: "models/peering/configuration.md"
        - Direct Peering Session: "models/peering/directpeeringsession.md"
        - E-mail: "models/peering/email.md"
        - Internet Exchange: "models/peering/internetexchange.md"
        - Internet Exchange Peering Session: "models/peering/internetexchangepeeringsession.md"
        - Platform: "models/devices/platform.md"
        - Router: "models/peering/router.md"
        - Routing Policy: "models/peering/routingpolicy.md"
        - Config Contexts: "models/peering/configcontexts.md"
        - Connection: "models/net/connection.md"
        - Token: "models/users/token.md"
        - Tag: "models/utils/tag.md"
        - Webhook: "models/webhooks/webhook.md"
    - Templating:
        - Writing Templates: "templating/index.md"
        - Jinja Filters: "templating/filters.md"
        - Exposed Variables: "templating/variables.md"
        - Templating Tutorial:
            - About: "templating/tutorial/index.md"
            - BGP Communities: "templating/tutorial/communities.md"
            - Policies: "templating/tutorial/policies.md"
            - Autonomous Systems: "templating/tutorial/as-template.md"
            - Using Tags: "templating/tutorial/tags.md"
        - Examples:
            - Arista EOS: "templating/examples/arista-eos.md"
            - Cisco IOS XR: "templating/examples/cisco-iosxr.md"
            - Cisco IOS XR as used by AS196610: "templating/examples/cisco-iosxr-as196610.md"
            - Juniper Junos OS: "templating/examples/juniper-junos.md"
            - Peering Request E-Mail: "templating/examples/peering-request-email.md"
    - Integration: "integration.md"
    - Development:
        - Getting Started: "development/getting-started.md"
        - Style Guide: "development/style-guide.md"
        - Release Engineering: "development/release-engineering.md"
