site_name: Peering Manager
repo_url: https://github.com/respawner/peering-manager

pages:
  - Introduction: 'index.md'
  - Setup:
    - '1. PostgreSQL': 'setup/1-postgresql.md'
    - '2. Peering Manager': 'setup/2-peering-manager.md'
    - '3. Web Server': 'setup/3-web-server.md'
    - '4. Logging (Optional)': 'setup/4-logging.md'
    - '5. LDAP (Optional)': 'setup/5-ldap.md'
    - '6. Scheduled Tasks (Optional)': 'setup/6-scheduled-tasks.md'
    - Upgrading: 'setup/upgrading.md'
    - Migrate to systemd: 'setup/migrate-to-systemd.md'
  - Configuration:
    - Configuring: 'configuration/index.md'
    - Required Settings: 'configuration/required-settings.md'
    - Optional Settings: 'configuration/optional-settings.md'
  - User Manual:
    - Autonomous System: 'templates/objects/autonomoussystem.md'
    - BGP Group: 'templates/objects/bgpgroup.md'
    - Community: 'templates/objects/community.md'
    - Direct Peering Session: 'templates/objects/directpeeringsession.md'
    - Internet Exchange: 'templates/objects/internetexchange.md'
    - Internet Exchange Peering Session: 'templates/objects/internetexchangepeeringsession.md'
    - Router: 'templates/objects/router.md'
    - Routing Policy: 'templates/objects/routingpolicy.md'
  - Templating:
    - Writing Templates: 'templates/index.md'
    - Juniper JUNOS: 'templates/juniper-junos.md'
    - Cisco IOS-XR: 'templates/cisco-iosxr.md'
    - Arista EOS: 'templates/arista-eos.md'
    - Peering Request E-mail: 'templates/peering-request-email.md'
  - Integration: 'integration.md'

theme: readthedocs
markdown_extensions:
    - admonition:
