---
blank_issues_enabled: false
contact_links:
  - name: â“ Discussion
    url: "https://github.com/peering-manager/peering-manager/discussions"
    about: "If you're just looking for help, try starting a discussion instead"
  - name: ğŸ’¬ Community Slack
    url: "https://netdev.chat/"
    about: "Join #peering-manager on the NetDev Community Slack for assistance"
